port = 8989
cors=true
gin_logger=true
dsn="root@tcp(localhost)/cross_share"
jwt_key="secretKey"
# unit: minute
expire=100

log_level="debug"

# unit: second
check_interval=2
# unit: second
expire_limit = 10